# Generated by Django 2.1.5 on 2019-01-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('navigation', models.IntegerField()),
                ('commerce', models.IntegerField()),
                ('recherche', models.IntegerField()),
                ('construction', models.IntegerField()),
                ('culture', models.IntegerField()),
                ('combat', models.IntegerField()),
            ],
        ),
    ]
